spring:
  application:
    name: auth-api
server:
  port: 8082

---
spring:
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.136:5432/webx_notify_db?createIfNotExists=true
    username: postgres
    password: postgres
    #data: classpath:/component-module-submodule.sql,classpath:/role.sql,classpath:/permissions.sql,classpath:/user-role.sql,classpath:/role_permission.sql,classpath:/url-data.sql,classpath:/api-endpoints.sql,classpath:/navigations.sql
    initialization-mode: always
  # JPA properties
 jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
## File Storage Properties
file:
# upload-dir: /home/docker/nayeem/test/uploads/product
 upload-dir: D:/webx/project/email-service/file/
